# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corsy < Formula
  desc "Corsy is a proxy injector for development to avoid CORS issues while building SPA applications.."
  homepage "https://github.com/sivsivsree/corsy#corsy"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.0/corsy_0.1.0_darwin_amd64.tar.gz"
      sha256 "64cb1688b2386e8a845d2195f334961963973386f8d7611f19c13e42b4fbe052"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.0/corsy_0.1.0_linux_amd64.tar.gz"
      sha256 "0cc908397c1183e4ef54cb543258c38f9d43f98f6c8021a316f8efcbf63b2870"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.0/corsy_0.1.0_linux_arm64.tar.gz"
      sha256 "5820388cbe1885e7bf3ebc88f151cca53bd662f1ed86080a4ba5fed1256d1f2f"
    end
  end

  def install
    bin.install "corsy"
  end

  def caveats; <<~EOS
    CORS injector proxy for development
  EOS
  end
end
