# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corsy < Formula
  desc "Corsy is a proxy injector for development to avoid CORS issues while building SPA applications.."
  homepage "https://github.com/sivsivsree/corsy#corsy"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.1/corsy_0.1.1_darwin_amd64.tar.gz"
      sha256 "befa8cb500fcaceed1cae7301a99c9954e17f7c80bd1865692181e848ea08d7d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.1/corsy_0.1.1_darwin_arm64.tar.gz"
      sha256 "d635939755f1039d0a49fa3451d579add7dcabb841b6884001760a50d4c1f2e4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.1/corsy_0.1.1_linux_amd64.tar.gz"
      sha256 "f3c24da3eff705fc172b9641c804283b83b2c197c19d6633fcec96b2fe2858b2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.1.1/corsy_0.1.1_linux_arm64.tar.gz"
      sha256 "1d920fa808d8a7257ce2abc4baf7159b989fbf2413eb9f371cfd074ee94a7270"
    end
  end

  def install
    bin.install "corsy"
  end

  def caveats; <<~EOS
    CORS injector proxy for development
  EOS
  end
end
