# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corsy < Formula
  desc "Corsy is a proxy injector for development to avoid CORS issues while building SPA applications.."
  homepage "https://github.com/sivsivsree/corsy#corsy"
  version "0.0.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.0.4/corsy_0.0.4_darwin_amd64.tar.gz"
      sha256 "8d835dfb997aa717080fb7a995a9ae58504c19e71a29b6648fa361c67394d0f4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.0.4/corsy_0.0.4_linux_amd64.tar.gz"
      sha256 "9d46883c3a0f2b02a52ac52303454b021753b308db0df96ea06eb3de9cf80db5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivsivsree/corsy/releases/download/v0.0.4/corsy_0.0.4_linux_arm64.tar.gz"
      sha256 "7c897882290792c48edc9fee906347a1ad6e3032f827fdb0337f1b78b26ec94f"
    end
  end

  def install
    bin.install "corsy"
  end

  def caveats; <<~EOS
    CORS injector proxy for development
  EOS
  end
end
