name: goreleaser

on:
 workflow_dispatch:

permissions:
  contents: write
  
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: -f .goreleaser.yml release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
